apiVersion: v1
kind: Service
metadata:
  name: k8s
spec:
  type: {{ .Values.service.type }}
  selector:
    app: k8s
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}